# Generated by Django 4.1 on 2022-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=225)),
                ('project_progress', models.CharField(max_length=50)),
                ('create_by', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
