# Generated by Django 4.1 on 2022-08-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
