# Generated by Django 4.1 on 2022-08-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0002_projects_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='level',
            new_name='priority',
        ),
    ]
