# Generated by Django 4.1 on 2022-08-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0003_rename_level_projects_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='priority',
            new_name='project_priority',
        ),
    ]
