# Generated by Django 4.1 on 2022-08-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0006_alter_projects_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
