# Generated by Django 4.1 on 2022-08-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0007_projects_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
